### ISSUE TITLE
README typo?

### ISSUE THREAD

**Issue by agladstein** [grahamgower/genomatnn#36]
Is `conda activate genomatnn` correct?

For me, only `source activate genomatnn` works.

**Comment by grahamgower** [comment]
I've double checked the conda docs, and it looks like `conda activate the_environment_name` is the way to activate the environment.
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment

The `source` command is a bash-shell builtin. `source filename` should load a shell script named `filename`. So I'm not sure why `source activate genomatnn` doesn't just give you an error (unless there's an 'activate' shell script in your current working directory?).

**Comment by agladstein** [comment]
Looks like its conda version incompatibility. 
I'm apparently running 4.3.27. The 4.6.0 instructions say: `source activate myenv`. So, you can probably ignore that. Or if you want to be nice you can put a note in for older versions of conda.

https://docs.conda.io/projects/conda/en/4.6.0/user-guide/tasks/manage-environments.html#activating-an-environment
