### ISSUE TITLE
Typo in demographic_models

### ISSUE THREAD

**Issue by xin-huang** [grahamgower/genomatnn#55]
Hi @grahamgower 

It looks like the population size of YRI should be 27600 (Gower et al. 2021 Appedix 3 Table 1), while the population size is 27000 in the demographic models.
https://github.com/grahamgower/genomatnn/blob/main/demographic_models/HomininComposite_4G20.yaml#L30
https://github.com/grahamgower/genomatnn/blob/main/demographic_models/HomininComposite2_4G20.yaml#L45

**Comment by grahamgower** [comment]
Nice catch! This value was taken from Kuhlwilm et al. 2016 ([Table S14](https://static-content.springer.com/esm/art%3A10.1038%2Fnature16544/MediaObjects/41586_2016_BFnature16544_MOESM27_ESM.pdf)), which does indicate N=27,600 for Yoruba. So it looks like I copied it into the demographic model incorrectly. The results in Gower et al. definitely used 27000. Oops! I'm glad it's only wrong by 2.2%!

**Comment by xin-huang** [comment]
I see. Thank you.
