### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by Apdulai** [grahamgower/genomatnn#56]
Hi, 
Having successfully installed the package under the conda environment on CentOS Linux, I encountered this error while doing the test. It seems to me that this is a problem with python, but I don't really know how to debug it. 
Thanks in advance 
Sincerely,
Apdulai

----------------------------------------

$ nosetests -v tests
test_upsample_indexes (tests.test_calibrate.TestUpsample) ... ok
test_upsample_indexes_weighted (tests.test_calibrate.TestUpsample) ... ok
test_apply_creates_predictions (tests.test_cli.TestApply) ... ok
test_missing_config_file (tests.test_cli.TestApply) ... ok
test_missing_nn_hdf5_file (tests.test_cli.TestApply) ... ok
test_apply_creates_predictions (tests.test_cli.TestApply_phased) ... ok
test_missing_config_file (tests.test_cli.TestApply_phased) ... ok
test_missing_nn_hdf5_file (tests.test_cli.TestApply_phased) ... ok
test_eval_creates_plots (tests.test_cli.TestEval) ... ok
test_missing_config_file (tests.test_cli.TestEval) ... ok
test_missing_nn_hdf5_file (tests.test_cli.TestEval) ... ok
test_eval_creates_plots (tests.test_cli.TestEval_phased) ... ok
test_missing_config_file (tests.test_cli.TestEval_phased) ... ok
test_missing_nn_hdf5_file (tests.test_cli.TestEval_phased) ... ok
test_list_modelspecs (tests.test_cli.TestSim) ... ok
test_missing_config_file (tests.test_cli.TestSim) ... ok
test_sim (tests.test_cli.TestSim) ... ok
test_missing_config_file (tests.test_cli.TestTrain) ... ok
test_train (tests.test_cli.TestTrain) ... ok
test_train_from_cache (tests.test_cli.TestTrain) ... ok
test_missing_config_file (tests.test_cli.TestVcfplot) ... ok
test_vcfplot_creates_plot (tests.test_cli.TestVcfplot) ... ok
test_min_coalescent_time_ancient_samples (tests.test_contact.TestContact) ... ok
test_split_time (tests.test_contact.TestContact) ... ok
test_tmcra (tests.test_contact.TestContact) ... ok
test_exclusion_of_drawn_mutation (tests.test_convert.TestDrawnMutation) ... ERROR
test_compare_ts_vcf_genotype_matrixes (tests.test_convert.TestGenotypeMatrixes) ... ok
test_ts_genotype_matrix (tests.test_convert.TestGenotypeMatrixes) ... ok
test_reorder (tests.test_convert.TestSorting) ... ok
test_sort_similarity (tests.test_convert.TestSorting) ... ok
test_ts_pop_counts_indices (tests.test_convert.TestSorting) ... ok
test_verify_partition (tests.test_convert.TestSorting) ... ok
test_gt_bytes2vec (tests.test_misc.TestMisc) ... ok
test_basic_cnn (tests.test_tfstuff.TestModelConstruction) ... ok
test_per_population_permutation_invariant_cnn (tests.test_tfstuff.TestModelConstruction) ... ok
test_permutation_invariant_cnn (tests.test_tfstuff.TestModelConstruction) ... ok
test_accumulate_matrices (tests.test_vcf.TestVCF) ... ok
test_bcftools_query (tests.test_vcf.TestVCF) ... ok
test_genotypes (tests.test_vcf.TestVCF) ... ok

======================================================================
ERROR: test_exclusion_of_drawn_mutation (tests.test_convert.TestDrawnMutation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/shared/ifbstor1/home/$USER/genomatnn/tests/test_convert.py", line 253, in test_exclusion_of_drawn_mutation
    ts = slim.simulate(
  File "/shared/home/$USER/.local/lib/python3.8/site-packages/stdpopsim/slim_engine.py", line 1027, in simulate
    ts = pyslim.load(ts_file.name)
  File "/shared/ifbstor1/home/$USER/genomatnn/.conda/envs/lib/python3.8/site-packages/pyslim/slim_tree_sequence.py", line 38, in load
    ts = SlimTreeSequence.load(path, legacy_metadata=legacy_metadata)
  File "/shared/ifbstor1/home/$USER/genomatnn/.conda/envs/lib/python3.8/site-packages/pyslim/slim_tree_sequence.py", line 225, in load
    return cls(ts, reference_sequence=reference_sequence, legacy_metadata=legacy_metadata)
  File "/shared/ifbstor1/home/$USER/genomatnn/.conda/envs/lib/python3.8/site-packages/pyslim/slim_tree_sequence.py", line 170, in __init__
    self.reference_sequence = reference_sequence
AttributeError: can't set attribute

**Comment by grahamgower** [comment]
Hi @Apdulai. This might be an incompatibility with the tskit version. Can you paste the output of `conda list` with your conda environment activated?

**Comment by Apdulai** [comment]
Thank you @grahamgower  for your  quick response

Here it is : 

$conda list 

# packages in environment at /shared/ifbstor1/home/abeye/genomatnn/.conda/envs:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
abseil-cpp                20210324.2           h9c3ff4c_0    conda-forge
absl-py                   0.15.0                   pypi_0    pypi
aiohttp                   3.8.1            py38h497a2fe_0    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
asciitree                 0.3.3                    pypi_0    pypi
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     20.3.0                   pypi_0    pypi
bcftools                  1.13                 h3a49de5_0    bioconda
blinker                   1.4                        py_1    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1003    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cachetools                4.2.4              pyhd8ed1ab_0    conda-forge
certifi                   2021.10.8        py38h578d9bd_1    conda-forge
cffi                      1.15.0           py38h3931269_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.0.4            py38h578d9bd_0    conda-forge
cryptography              36.0.1           py38h3e25421_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.21                  pypi_0    pypi
fasteners                 0.17.3                   pypi_0    pypi
frozenlist                1.3.0            py38h497a2fe_0    conda-forge
gast                      0.3.3                      py_0    conda-forge
genomatnn                 0.1.dev147+g9c637bf          pypi_0    pypi
giflib                    5.2.1                h36c2ea0_2    conda-forge
google-auth               1.35.0             pyh6c4a22f_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grpc-cpp                  1.37.1               hfc4d69e_3    conda-forge
grpcio                    1.37.1           py38hdd6454d_0    conda-forge
gsl                       2.6                  he838d99_2    conda-forge
h5py                      2.10.0          nompi_py38h9915d05_106    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
htslib                    1.13                 h9093b5e_0    bioconda
humanize                  4.0.0              pyhd8ed1ab_0    conda-forge
icu                       68.2                 h9c3ff4c_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imageio                   2.15.0                   pypi_0    pypi
importlib-metadata        4.11.2           py38h578d9bd_0    conda-forge
importlib_metadata        4.11.2               hd8ed1ab_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h7f98852_0    conda-forge
jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
kastore                   0.3.1            py38h6c62de6_3    conda-forge
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.3.2                    pypi_0    pypi
krb5                      1.19.2               h3790be6_4    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           13_linux64_openblas    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libcurl                   7.82.0               h7bff187_0    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_13    conda-forge
libgfortran-ng            11.2.0              h69a702a_13    conda-forge
libgfortran5              11.2.0              h5c6108e_13    conda-forge
libgomp                   11.2.0              h1d223b6_13    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libprotobuf               3.15.8               h780b84a_1    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_13    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
markdown                  3.3.6              pyhd8ed1ab_0    conda-forge
matplotlib                3.3.3                    pypi_0    pypi
msprime                   0.7.4            py38h55b2093_3    conda-forge
multidict                 6.0.2            py38h497a2fe_0    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
nose                      1.3.7                    pypi_0    pypi
numcodecs                 0.9.1                    pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.2.0              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pillow                    9.0.1                    pypi_0    pypi
pip                       21.2.2             pyhd8ed1ab_0    conda-forge
protobuf                  3.15.8           py38h709712a_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyjwt                     2.3.0              pyhd8ed1ab_1    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1           py38h497a2fe_0    conda-forge
pyslim                    0.600              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_4    conda-forge
python                    3.8.12          ha38a3c6_3_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-flatbuffers        1.12               pyhd8ed1ab_1    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
re2                       2021.08.01           h9c3ff4c_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rsa                       4.8                pyhd8ed1ab_0    conda-forge
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.8.0            py38h56a6a73_1    conda-forge
setuptools                60.9.3           py38h578d9bd_0    conda-forge
six                       1.15.0                   pypi_0    pypi
slim                      3.6                  h9c3ff4c_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
svgwrite                  1.4.1              pyhd8ed1ab_0    conda-forge
tensorboard               2.4.1              pyhd8ed1ab_1    conda-forge
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
tensorflow                2.4.1            py38h578d9bd_0    conda-forge
tensorflow-base           2.4.1            py38h83f5f1d_0    conda-forge
tensorflow-estimator      2.4.0              pyh9656e83_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tf-keras-vis              0.5.5                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2                   pypi_0    pypi
tskit                     0.4.1            py38h6c62de6_0    conda-forge
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
werkzeug                  2.0.3              pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h516909a_1    conda-forge
yarl                      1.7.2            py38h497a2fe_1    conda-forge
zarr                      2.5.0                    pypi_0    pypi
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge

**Comment by Apdulai** [comment]
Thank you @grahamgower for your quick response

Here it is :
`$ conda list`

`# packages in environment at /shared/ifbstor1/home/abeye/genomatnn/.conda/envs:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
abseil-cpp                20210324.2           h9c3ff4c_0    conda-forge
absl-py                   0.15.0                   pypi_0    pypi
aiohttp                   3.8.1            py38h497a2fe_0    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
asciitree                 0.3.3                    pypi_0    pypi
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     20.3.0                   pypi_0    pypi
bcftools                  1.13                 h3a49de5_0    bioconda
blinker                   1.4                        py_1    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1003    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cachetools                4.2.4              pyhd8ed1ab_0    conda-forge
certifi                   2021.10.8        py38h578d9bd_1    conda-forge
cffi                      1.15.0           py38h3931269_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.0.4            py38h578d9bd_0    conda-forge
cryptography              36.0.1           py38h3e25421_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.21                  pypi_0    pypi
fasteners                 0.17.3                   pypi_0    pypi
frozenlist                1.3.0            py38h497a2fe_0    conda-forge
gast                      0.3.3                      py_0    conda-forge
genomatnn                 0.1.dev147+g9c637bf          pypi_0    pypi
giflib                    5.2.1                h36c2ea0_2    conda-forge
google-auth               1.35.0             pyh6c4a22f_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grpc-cpp                  1.37.1               hfc4d69e_3    conda-forge
grpcio                    1.37.1           py38hdd6454d_0    conda-forge
gsl                       2.6                  he838d99_2    conda-forge
h5py                      2.10.0          nompi_py38h9915d05_106    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
htslib                    1.13                 h9093b5e_0    bioconda
humanize                  4.0.0              pyhd8ed1ab_0    conda-forge
icu                       68.2                 h9c3ff4c_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imageio                   2.15.0                   pypi_0    pypi
importlib-metadata        4.11.2           py38h578d9bd_0    conda-forge
importlib_metadata        4.11.2               hd8ed1ab_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h7f98852_0    conda-forge
jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
kastore                   0.3.1            py38h6c62de6_3    conda-forge
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.3.2                    pypi_0    pypi
krb5                      1.19.2               h3790be6_4    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           13_linux64_openblas    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libcurl                   7.82.0               h7bff187_0    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_13    conda-forge
libgfortran-ng            11.2.0              h69a702a_13    conda-forge
libgfortran5              11.2.0              h5c6108e_13    conda-forge
libgomp                   11.2.0              h1d223b6_13    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libprotobuf               3.15.8               h780b84a_1    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_13    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
markdown                  3.3.6              pyhd8ed1ab_0    conda-forge
matplotlib                3.3.3                    pypi_0    pypi
msprime                   0.7.4            py38h55b2093_3    conda-forge
multidict                 6.0.2            py38h497a2fe_0    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
nose                      1.3.7                    pypi_0    pypi
numcodecs                 0.9.1                    pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.2.0              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pillow                    9.0.1                    pypi_0    pypi
pip                       21.2.2             pyhd8ed1ab_0    conda-forge
protobuf                  3.15.8           py38h709712a_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyjwt                     2.3.0              pyhd8ed1ab_1    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1           py38h497a2fe_0    conda-forge
pyslim                    0.600              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_4    conda-forge
python                    3.8.12          ha38a3c6_3_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-flatbuffers        1.12               pyhd8ed1ab_1    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
re2                       2021.08.01           h9c3ff4c_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rsa                       4.8                pyhd8ed1ab_0    conda-forge
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.8.0            py38h56a6a73_1    conda-forge
setuptools                60.9.3           py38h578d9bd_0    conda-forge
six                       1.15.0                   pypi_0    pypi
slim                      3.6                  h9c3ff4c_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
svgwrite                  1.4.1              pyhd8ed1ab_0    conda-forge
tensorboard               2.4.1              pyhd8ed1ab_1    conda-forge
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
tensorflow                2.4.1            py38h578d9bd_0    conda-forge
tensorflow-base           2.4.1            py38h83f5f1d_0    conda-forge
tensorflow-estimator      2.4.0              pyh9656e83_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tf-keras-vis              0.5.5                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2                   pypi_0    pypi
tskit                     0.4.1            py38h6c62de6_0    conda-forge
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
werkzeug                  2.0.3              pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h516909a_1    conda-forge
yarl                      1.7.2            py38h497a2fe_1    conda-forge
zarr                      2.5.0                    pypi_0    pypi
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
`

**Comment by grahamgower** [comment]
Can you try installing an older version of tskit? E.g. `conda install 'tskit<0.4'`? That's the first thing that comes to mind, without trying to reproduce the problem locally.

**Comment by Apdulai** [comment]
I have installed the version tskit==0.3.4, and retried again, which unfortunately still fails at the same level.

![image](https://user-images.githubusercontent.com/69516027/157726956-634444a6-a343-46b0-a322-5faa274ed4d5.png)

**Comment by grahamgower** [comment]
I reproduced the problem using the installation instructions from the README. I then downgraded to tskit 0.3.7 with the command `conda install "tskit<0.4"`. I then reran the tests, which succeeded. So I'll update the environment.yml file to specify a compatible version of tskit.

I'm not sure why it failed for you after downgrading tskit, but it's possible there's some other tskit installation in your Python environment that is being used in preference to the one installed in your conda env (e.g. if you have pip-installed something into your $HOME/.local/lib/python3.8/ this can cause conflicts). You can confirm/deny this by running
```
python -c "import tskit; print(tskit.__version__); print(tskit.__file__)"
```
For me, this outputs the following, which confirms that Python is using 0.3.7 from my current conda environment (named gm-test)
```
0.3.7
/home/srx907/miniconda3/envs/gm-test/lib/python3.8/site-packages/tskit/__init__.py
```

**Comment by grahamgower** [comment]
Thanks for reporting the problem @Apdulai! Please let me know if you can't get it working - maybe starting with a fresh conda environment will help. Anyhow, I think I've fixed this now.

**Comment by Apdulai** [comment]
Hi, 
I don't really know where the trouble comes from then, because when I do ` python -c "import tskit; print(tskit.__version__); print(tskit.__file__)"` I get `0.3.4
/home/beyea/.conda/envs/genomatnn/lib/python3.8/site-packages/tskit/__init__.py`

**Comment by Apdulai** [comment]
I will restart the installation process and let you know if the bug still occurs. Thanks for your support though!

**Comment by Apdulai** [comment]
Finally, going through the complete process of installation from the beginning, with the `tskit==0.3.7`, everything works correctly. 
Thanks again!
Sincerely,

![image](https://user-images.githubusercontent.com/69516027/157902474-5eb702d3-ce9e-4f99-84c0-98fdd0f2d2a9.png)
